import React, { useState } from 'react';
import './App.css';

function App() {
  const [result, setResult] = useState("Waiting for resume...");
  const [jobRole, setJobRole] = useState(""); 
  const [selectedFile, setSelectedFile] = useState(null);
  const [skills, setSkills] = useState([]);
  const [thoughts, setThoughts] = useState([]); 

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      setSelectedFile(file);
      setResult(`📄 "${file.name}" uploaded. Define your goal and start.`);
    }
  };

  const downloadReport = () => {
    const content = `VIDYAGUIDE AI AGENT REPORT\n\nTarget Role: ${jobRole}\nStatus: ${result}\nRecommended Skills: ${skills.join(", ")}\n\nGenerated by VidyaGuide AI.`;
    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "VidyaGuide_AI_Report.txt";
    document.body.appendChild(element);
    element.click();
  };

  const runAnalysis = () => {
    if (!jobRole || !selectedFile) {
      alert("Please enter a job role AND upload a resume!");
      return;
    }

    setSkills([]);
    setThoughts(["Initializing VidyaGuide AI Agent..."]);
    setResult("🤖 Agent is active...");

    setTimeout(() => {
      setThoughts(prev => [...prev, "🔍 Parsing PDF structure... Detected 'Experience' and 'Skills' sections."]);
    }, 1000);

    setTimeout(() => {
      setThoughts(prev => [...prev, `🌐 Searching industry requirements for '${jobRole}'...`]);
    }, 2500);

    setTimeout(() => {
      setThoughts(prev => [...prev, "📊 Comparing resume keywords against market demand..."]);
    }, 4000);

    setTimeout(() => {
      const role = jobRole.toLowerCase();
      if (role.includes("game")) {
        setSkills(["Unity/Unreal Engine", "C++ & C#", "3D Math", "Physics Engines"]);
      } else if (role.includes("web") || role.includes("dev")) {
        setSkills(["React & Next.js", "Node.js", "TypeScript", "Tailwind CSS"]);
      } else {
        setSkills(["Strategic Planning", "Project Management", "Critical Thinking", "Problem Solving"]);
      }
      setResult(`✅ Analysis Complete for ${selectedFile.name}.`);
      setThoughts(prev => [...prev, "🏁 Final Report Generated."]);
    }, 5500);
  };

  return (
    <div className="App">
      <nav className="navbar">
        <div className="nav-content"><h2>VidyaGuide AI Agent 🚀</h2></div>
      </nav>

      <div className="container">
        <section className="card">
          <span className="step-tag">Step 1</span>
          <h3>Target Goal</h3>
          <input className="main-input" type="text" placeholder="e.g. Game Developer" value={jobRole} onChange={(e) => setJobRole(e.target.value)} />
        </section>

        <section className="card">
          <span className="step-tag">Step 2</span>
          <h3>Resume Upload</h3>
          <input type="file" onChange={handleFileChange} id="file-upload" hidden />
          <label htmlFor="file-upload" className="file-btn">
            {selectedFile ? `📄 ${selectedFile.name}` : "📁 Select Resume"}
          </label>
        </section>

        <section className="card">
          <span className="step-tag">Step 3</span>
          <h3>AI Action</h3>
          <p className="status-box">{result}</p>
          <button className="scan-btn" onClick={runAnalysis}>Start Agentic Scan</button>
        </section>

        {thoughts.length > 0 && (
          <section className="card console-card">
            <h3>Agent Reasoning Log</h3>
            <div className="console">
              {thoughts.map((t, i) => <p key={i} className="thought-line">{t}</p>)}
            </div>
          </section>
        )}

        {skills.length > 0 && (
          <section className="card result-box">
            <h3>AI Recommendations for {jobRole}</h3>
            <div className="skill-grid">
              {skills.map((s, i) => <div key={i} className="skill-tag">{s}</div>)}
            </div>
            <button className="download-btn" onClick={downloadReport}>📥 Download Report</button>
          </section>
        )}
      </div>
    </div>
  );
}

export default App;